# Generated by Django 5.2.7 on 2025-10-29 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='core.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(max_length=10, unique=True, verbose_name='Localizador')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='core.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'pais')},
            },
        ),
    ]
