# Generated by Django 5.2.7 on 2025-11-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Sector básico',
                'verbose_name_plural': 'Sectores básicos',
                'db_table': 'core_basico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'core_ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, default='', max_length=50, verbose_name='Segundo Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'db_table': 'core_guia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'core_pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (vías de contacto)',
                'verbose_name_plural': 'Tipos (vías de contacto)',
                'db_table': 'core_tipo_causa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (momento)',
                'verbose_name_plural': 'Tipos (momento)',
                'db_table': 'core_tipo_momento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (pagador)',
                'verbose_name_plural': 'Tipos (pagador)',
                'db_table': 'core_tipo_pagador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (remitente)',
                'verbose_name_plural': 'Tipos (remitente)',
                'db_table': 'core_tipo_remitente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransferistaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (transferista - incidencia)',
                'verbose_name_plural': 'Tipos (transferista - incidencia)',
                'db_table': 'core_tipo_transferista_incidencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransferistaPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (transferista - punto)',
                'verbose_name_plural': 'Tipos (transferista - punto)',
                'db_table': 'core_tipo_transferista_punto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransferistaRazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (transferista - razón)',
                'verbose_name_plural': 'Tipos (transferista - razón)',
                'db_table': 'core_tipo_transferista_razon',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoViaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (vías de contacto)',
                'verbose_name_plural': 'Tipos (vías de contacto)',
                'db_table': 'core_tipo_via_contacto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Hotel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='core.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'core_hotel',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='core.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'db_table': 'core_operador',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='core.pais', verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(max_length=10, unique=True, verbose_name='Localizador')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'core_reserva',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('conductor', models.BooleanField(default=False)),
                ('averia', models.BooleanField(default=False)),
                ('equipaje', models.BooleanField(default=False)),
                ('accidente', models.BooleanField(default=False)),
                ('otro', models.BooleanField(default=False)),
                ('basico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.basico')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte_destino', to='core.ciudad', verbose_name='Ciudad de destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte_origen', to='core.ciudad', verbose_name='Ciudad de origen')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte', to='core.reserva', verbose_name='Reserva')),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (transporte)',
                'verbose_name_plural': 'Incidencias (transportes)',
                'db_table': 'core_incidencia_transporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaTransferista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transferista', to='core.ciudad', verbose_name='Ciudad')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transferista_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transferista', to='core.reserva', verbose_name='Reserva')),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipotransferistaincidencia', verbose_name='Incidencia')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipotransferistapunto', verbose_name='Punto del viaje')),
                ('razon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipotransferistarazon', verbose_name='Razón')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (transferista)',
                'verbose_name_plural': 'Incidencias (transferista)',
                'db_table': 'core_incidencia_transferista',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaOpcionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('incidencia', models.CharField(choices=[('NRL', 'No realizado'), ('QLT', 'Calidad del servicio'), ('IMP', 'Impago')], db_index=True, max_length=3, verbose_name='Incidencia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcionales', to='core.ciudad', verbose_name='Ciudad')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcionales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcionales', to='core.reserva', verbose_name='Reserva')),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (opcional)',
                'verbose_name_plural': 'Incidencias (opcionales)',
                'db_table': 'core_incidencia_opcional',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('room_key', models.BooleanField(default=False)),
                ('room_clean', models.BooleanField(default=False)),
                ('room_size', models.BooleanField(default=False)),
                ('room_bed_type', models.BooleanField(default=False)),
                ('room_facility', models.BooleanField(default=False)),
                ('room_amenity', models.BooleanField(default=False)),
                ('room_maintenance', models.BooleanField(default=False)),
                ('restaurant_personal', models.BooleanField(default=False)),
                ('restaurant_quantity', models.BooleanField(default=False)),
                ('restaurant_quality', models.BooleanField(default=False)),
                ('reserve_non_booking', models.BooleanField(default=False)),
                ('reserve_city_tax', models.BooleanField(default=False)),
                ('reserve_location', models.BooleanField(default=False)),
                ('other_personal', models.BooleanField(default=False)),
                ('other_lobby_size', models.BooleanField(default=False)),
                ('causa', models.CharField(choices=[('HTL', 'Error Hotel'), ('EMV', 'Error EMV'), ('UNK', 'Desconocido')], db_index=True, max_length=3, verbose_name='Causa (Hotel)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_hotel_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hotel')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_hotel', to='core.reserva', verbose_name='Reserva')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (hotel)',
                'verbose_name_plural': 'Incidencias (hotel)',
                'db_table': 'core_incidencia_hotel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('personal', models.BooleanField(default=False)),
                ('gestion', models.BooleanField(default=False)),
                ('conocimiento', models.BooleanField(default=False)),
                ('idioma', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('otro', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_guia_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.guia')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_guia', to='core.reserva', verbose_name='Reserva')),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (guía)',
                'verbose_name_plural': 'Incidencias (guías)',
                'db_table': 'core_incidencia_guia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.reserva', verbose_name='Reserva')),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (demo)',
                'verbose_name_plural': 'Incidencias (demo)',
                'db_table': 'core_incidencia_demo',
            },
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('nombre', 'ciudad'), name='unique_hotel_per_city'),
        ),
        migrations.AlterUniqueTogether(
            name='operador',
            unique_together={('nombre', 'pais')},
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre', 'pais')},
        ),
    ]
