# Generated by Django 5.2.7 on 2025-10-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Hotel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='core.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'ciudad'), name='unique_hotel_per_city')],
            },
        ),
    ]
