# Generated by Django 5.2.7 on 2025-11-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOpcionalIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo (opcional - incidencia)',
                'verbose_name_plural': 'Tipos (opcional - incidencia)',
                'db_table': 'core_tipo_opcional_incidencia',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipocausa',
            options={'ordering': ['id'], 'verbose_name': 'Tipo (causa)', 'verbose_name_plural': 'Tipos (causas)'},
        ),
        migrations.AlterField(
            model_name='incidenciaopcional',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoopcionalincidencia', verbose_name='Incidencia'),
        ),
    ]
