# Generated by Django 5.2.7 on 2025-11-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incidenciademo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, default='', max_length=50, verbose_name='Segundo Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'ordering': ['nombre'],
            },
        ),
    ]
