# Generated by Django 5.2.7 on 2025-11-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipootroincidencia_incidenciaotro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='other_lobby_size',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='other_personal',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='reserve_city_tax',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='reserve_location',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='reserve_non_booking',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='restaurant_personal',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='restaurant_quality',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='restaurant_quantity',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_amenity',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_bed_type',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_clean',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_facility',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_key',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_maintenance',
        ),
        migrations.RemoveField(
            model_name='incidenciahotel',
            name='room_size',
        ),
        migrations.AddField(
            model_name='incidenciahotel',
            name='habitacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenciahotel',
            name='otro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenciahotel',
            name='restaurante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidenciademo',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciaguia',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidenciaopcional',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciaotro',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciatransporte',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=500, verbose_name='Comentario'),
        ),
    ]
