# Generated by Django 5.2.7 on 2025-11-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_incidenciahotel_other_lobby_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciahotel',
            name='causa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa'),
        ),
    ]
