# Generated by Django 5.2.7 on 2025-11-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_incidenciademo_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Sector básico',
                'verbose_name_plural': 'Sectores básicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('PRE', 'Antes del viaje'), ('DUR', 'Durante el viaje'), ('POST', 'Después del viaje')], db_index=True, max_length=5, verbose_name='Momento del viaje')),
                ('remitente', models.CharField(choices=[('CLI', 'Cliente'), ('HOT', 'Hotel'), ('GUI', 'Guía'), ('AGE', 'Agencia'), ('INT', 'Interno'), ('OTR', 'Otro')], db_index=True, max_length=3, verbose_name='Remitente')),
                ('via', models.CharField(choices=[('TEL', 'Teléfono'), ('EML', 'Email'), ('WHA', 'WhatsApp'), ('OTR', 'Otros')], db_index=True, max_length=3, verbose_name='Vía de contacto')),
                ('pagador', models.CharField(choices=[('EMV', 'EMV'), ('CLI', 'Cliente'), ('AGE', 'Agencia'), ('NON', 'Nadie')], db_index=True, max_length=3, verbose_name='Pagador')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('conductor', models.BooleanField(default=False)),
                ('averia', models.BooleanField(default=False)),
                ('equipaje', models.BooleanField(default=False)),
                ('accidente', models.BooleanField(default=False)),
                ('otro', models.BooleanField(default=False)),
                ('basico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.basico')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte_destino', to='core.ciudad', verbose_name='Ciudad de destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte_origen', to='core.ciudad', verbose_name='Ciudad de origen')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transporte', to='core.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Incidencia (transporte)',
                'verbose_name_plural': 'Incidencias (transportes)',
                'ordering': ['-created_at'],
            },
        ),
    ]
