# Generated by Django 5.2.7 on 2025-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incidenciamonumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciademo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciaguia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciahotel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciamonumento',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciaopcional',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciaotro',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciatransferista',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
        migrations.AddField(
            model_name='incidenciatransporte',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Borrado'),
        ),
    ]
