# Generated by Django 5.2.7 on 2025-11-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_basico_incidenciatransporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='basico',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='IncidenciaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('PRE', 'Antes del viaje'), ('DUR', 'Durante el viaje'), ('POST', 'Después del viaje')], db_index=True, max_length=5, verbose_name='Momento del viaje')),
                ('remitente', models.CharField(choices=[('CLI', 'Cliente'), ('HOT', 'Hotel'), ('GUI', 'Guía'), ('AGE', 'Agencia'), ('INT', 'Interno'), ('OTR', 'Otro')], db_index=True, max_length=3, verbose_name='Remitente')),
                ('via', models.CharField(choices=[('TEL', 'Teléfono'), ('EML', 'Email'), ('WHA', 'WhatsApp'), ('OTR', 'Otros')], db_index=True, max_length=3, verbose_name='Vía de contacto')),
                ('pagador', models.CharField(choices=[('EMV', 'EMV'), ('CLI', 'Cliente'), ('AGE', 'Agencia'), ('NON', 'Nadie')], db_index=True, max_length=3, verbose_name='Pagador')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('room_key', models.BooleanField(default=False)),
                ('room_clean', models.BooleanField(default=False)),
                ('room_size', models.BooleanField(default=False)),
                ('room_bed_type', models.BooleanField(default=False)),
                ('room_facility', models.BooleanField(default=False)),
                ('room_amenity', models.BooleanField(default=False)),
                ('room_maintenance', models.BooleanField(default=False)),
                ('restaurant_personal', models.BooleanField(default=False)),
                ('restaurant_quantity', models.BooleanField(default=False)),
                ('restaurant_quality', models.BooleanField(default=False)),
                ('reserve_non_booking', models.BooleanField(default=False)),
                ('reserve_city_tax', models.BooleanField(default=False)),
                ('reserve_location', models.BooleanField(default=False)),
                ('other_personal', models.BooleanField(default=False)),
                ('other_lobby_size', models.BooleanField(default=False)),
                ('causa', models.CharField(choices=[('HTL', 'Error Hotel'), ('EMV', 'Error EMV'), ('UNK', 'Desconocido')], db_index=True, max_length=3, verbose_name='Causa (Hotel)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_hotel_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hotel')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_hotel', to='core.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Incidencia (hotel)',
                'verbose_name_plural': 'Incidencias (hotel)',
                'ordering': ['-created_at'],
            },
        ),
    ]
