# Generated by Django 5.2.7 on 2025-11-06 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_basico_nombre_incidenciahotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaTransferista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('PRE', 'Antes del viaje'), ('DUR', 'Durante el viaje'), ('POST', 'Después del viaje')], db_index=True, max_length=5, verbose_name='Momento del viaje')),
                ('remitente', models.CharField(choices=[('CLI', 'Cliente'), ('HOT', 'Hotel'), ('GUI', 'Guía'), ('AGE', 'Agencia'), ('INT', 'Interno'), ('OTR', 'Otro')], db_index=True, max_length=3, verbose_name='Remitente')),
                ('via', models.CharField(choices=[('TEL', 'Teléfono'), ('EML', 'Email'), ('WHA', 'WhatsApp'), ('OTR', 'Otros')], db_index=True, max_length=3, verbose_name='Vía de contacto')),
                ('pagador', models.CharField(choices=[('EMV', 'EMV'), ('CLI', 'Cliente'), ('AGE', 'Agencia'), ('NON', 'Nadie')], db_index=True, max_length=3, verbose_name='Pagador')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('punto', models.CharField(choices=[('APT/HTL', 'Aeropuerto / Hotel'), ('HTL/APT', 'Hotel / Aeropuerto'), ('TER/HTL', 'Terminal de buses / Hotel'), ('HTL/TER', 'Hotel / Terminal de buses'), ('HTL/HTL', 'Hotel / Hotel'), ('STN/HTL', 'Estación de tren / Hotel'), ('HTL/STN', 'Hotel / Estación de tren'), ('PRT/HTL', 'Puerto marítimo / Hotel'), ('HTL/PRT', 'Hotel / Puerto marítimo')], db_index=True, max_length=7, verbose_name='Punto del transfer')),
                ('incidencia', models.CharField(choices=[('PAX_NO_SHOW', 'Pasajero ausente'), ('TRF_ERROR', 'Error del transferista'), ('MISS_MEET', 'Encuentro no efectuado'), ('OTHERS', 'Otros')], db_index=True, max_length=20, verbose_name='Incidencia')),
                ('causa', models.CharField(choices=[('FLT_DELAY', 'Vuelo retrasado'), ('FLT_CHANGE', 'Cambio de vuelo'), ('LOST_BAGGAGE', 'Equipaje perdido'), ('APT_SVC_DELAY', 'Administración aeropuerto'), ('PAX_ERROR', 'Error PAX'), ('TRF_ERROR', 'Error transferista'), ('UNKNOWN', 'Desconocido')], db_index=True, max_length=20, verbose_name='Causa')),
                ('pax_avisado', models.BooleanField(default=False)),
                ('factura', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Incidencia (transferista)',
                'verbose_name_plural': 'Incidencias (transferista)',
                'ordering': ['-created_at'],
            },
        ),
    ]
