# Generated by Django 5.2.7 on 2025-11-18 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_incidenciademo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciahotel',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_hotel', to='core.reserva', verbose_name='Reserva'),
        ),
    ]
