# Generated by Django 5.2.7 on 2025-11-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_incidenciatransferista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transferista', to='core.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transferista_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_transferista', to='core.reserva', verbose_name='Reserva'),
        ),
        migrations.CreateModel(
            name='IncidenciaOpcionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('PRE', 'Antes del viaje'), ('DUR', 'Durante el viaje'), ('POST', 'Después del viaje')], db_index=True, max_length=5, verbose_name='Momento del viaje')),
                ('remitente', models.CharField(choices=[('CLI', 'Cliente'), ('HOT', 'Hotel'), ('GUI', 'Guía'), ('AGE', 'Agencia'), ('INT', 'Interno'), ('OTR', 'Otro')], db_index=True, max_length=3, verbose_name='Remitente')),
                ('via', models.CharField(choices=[('TEL', 'Teléfono'), ('EML', 'Email'), ('WHA', 'WhatsApp'), ('OTR', 'Otros')], db_index=True, max_length=3, verbose_name='Vía de contacto')),
                ('pagador', models.CharField(choices=[('EMV', 'EMV'), ('CLI', 'Cliente'), ('AGE', 'Agencia'), ('NON', 'Nadie')], db_index=True, max_length=3, verbose_name='Pagador')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 1000)', max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('incidencia', models.CharField(choices=[('NRL', 'No realizado'), ('QLT', 'Calidad del servicio'), ('IMP', 'Impago')], db_index=True, max_length=3, verbose_name='Incidencia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcionales', to='core.ciudad', verbose_name='Ciudad')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcionales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcionales', to='core.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Incidencia (opcional)',
                'verbose_name_plural': 'Incidencias (opcionales)',
                'ordering': ['-created_at'],
            },
        ),
    ]
