# Generated by Django 5.2.7 on 2025-11-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_incidenciahotel_reserve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidenciahotel',
            old_name='reserve',
            new_name='reservation',
        ),
    ]
