# Generated by Django 5.2.7 on 2025-11-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pax_avisado_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de momento',
                'verbose_name_plural': 'Tipos de momento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de pagador',
                'verbose_name_plural': 'Tipos de pagador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de remitente',
                'verbose_name_plural': 'Tipos de remitente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoViaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de vía de contacto',
                'verbose_name_plural': 'Tipos de vía de contacto',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='incidenciademo',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje'),
        ),
        migrations.AlterField(
            model_name='incidenciaguia',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje'),
        ),
        migrations.AlterField(
            model_name='incidenciaopcionales',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje'),
        ),
        migrations.AlterField(
            model_name='incidenciatransporte',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje'),
        ),
        migrations.AlterField(
            model_name='incidenciademo',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='incidenciaguia',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='incidenciaopcionales',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='incidenciatransporte',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='incidenciademo',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='incidenciaguia',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='incidenciaopcionales',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='incidenciatransporte',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='incidenciademo',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto'),
        ),
        migrations.AlterField(
            model_name='incidenciaguia',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto'),
        ),
        migrations.AlterField(
            model_name='incidenciaopcionales',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto'),
        ),
        migrations.AlterField(
            model_name='incidenciatransporte',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto'),
        ),
    ]
