# Generated by Django 5.2.6 on 2025-11-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_incidenciahotel_ubicacion_incidenciaitinerario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidenciaTicket',
        ),
    ]
