# Generated by Django 5.2.6 on 2025-11-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_incidenciaticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidenciaVueloIncluido',
        ),
    ]
