# Generated by Django 5.2.6 on 2025-11-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_incidenciavueloincluido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidenciaMonumento',
        ),
    ]
