# Generated by Django 5.2.6 on 2025-11-20 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_incidenciamonumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenciaitinerario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incidencia (general)', 'verbose_name_plural': 'Incidencias (general)'},
        ),
        migrations.RemoveField(
            model_name='incidenciaitinerario',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='incidenciaitinerario',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='incidenciaitinerario',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='incidenciaitinerario',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='incidenciaitinerario',
            name='trip',
        ),
        migrations.AddField(
            model_name='incidenciaitinerario',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_itinerario_destino', to='core.ciudad', verbose_name='Ciudad de destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenciaitinerario',
            name='inc_billetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenciaitinerario',
            name='inc_comidas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenciaitinerario',
            name='inc_entradas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenciaitinerario',
            name='inc_guia_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidenciaitinerario',
            name='inc_itinerario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidenciademo',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciaguia',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciahotel',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciaitinerario',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciaopcional',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciaotro',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciatransferista',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='incidenciatransporte',
            name='comentario',
            field=models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.CreateModel(
            name='IncidenciaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('inc_personal', models.BooleanField(default=False)),
                ('inc_seguro', models.BooleanField(default=False)),
                ('inc_otros', models.BooleanField(default=False)),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_general_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_general', to='core.reserva', verbose_name='Reserva')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (general)',
                'verbose_name_plural': 'Incidencias (general)',
                'db_table': 'core_incidencia_general',
                'ordering': ['-created_at'],
            },
        ),
    ]
