# Generated by Django 5.2.7 on 2025-11-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_incidenciaitinerario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenciaitinerario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incidencia (itinerario)', 'verbose_name_plural': 'Incidencias (itinerario)'},
        ),
        migrations.AlterField(
            model_name='incidenciaitinerario',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_itinerario_destino', to='core.ciudad', verbose_name='Ciudad'),
        ),
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opcionales', to='core.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Opcional',
                'verbose_name_plural': 'Opcionales',
                'db_table': 'core_opcional',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='IncidenciaOpcional',
        ),
    ]
