# Generated by Django 5.2.7 on 2025-11-21 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_incidenciaitinerario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaOpcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe (€)')),
                ('comentario', models.TextField(help_text='Información adicional del caso (máx. 500)', max_length=1000, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('inc_no_realizado', models.BooleanField(default=False)),
                ('inc_devolucion', models.BooleanField(default=False)),
                ('inc_pack', models.BooleanField(default=False)),
                ('inc_otros', models.BooleanField(default=False)),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipocausa', verbose_name='Causa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcional_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomomento', verbose_name='Momento del viaje')),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.opcional', verbose_name='Opcional')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipopagador', verbose_name='Pagador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiporemitente', verbose_name='Remitente')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_opcional', to='core.reserva', verbose_name='Reserva')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoviacontacto', verbose_name='Vía de contacto')),
            ],
            options={
                'verbose_name': 'Incidencia (opcional)',
                'verbose_name_plural': 'Incidencias (opcional)',
                'db_table': 'core_incidencia_opcional',
                'ordering': ['-created_at'],
            },
        ),
    ]
