# Generated by Django 5.2.7 on 2025-11-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_incidenciaopcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciatransferista',
            name='razon',
        ),
        migrations.DeleteModel(
            name='TipoTransferistaRazon',
        ),
    ]
